---

- name: Clone dotfile repository
  git:
    repo: "{{ dotfile_repo }}"
    dest: "/home/{{ username }}/ws/dotfiles"

- name: Link dotfile apps to .config
  file:
    src:  "/home/{{ username }}/ws/dotfiles/{{ item }}"
    dest: "/home/{{ username }}/.config/{{ item }}"
    state: link
  with_items: "{{ dotfiles_apps }}"

- name: Link dotfile fonts to .local/share/fonts
  file:
    src: "/home/{{ username }}/ws/dotfiles/other/fonts"
    dest: "/home/{{ username }}/.local/share/fonts"
    state: link

