---

- name: Change user shell to zsh
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Delete .bash files in home directory
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: absent
  with_items:
    - ".bashrc"
    - ".bash_logout"
    - ".bash_profile"

# sway
- name: Enable dbus
  service: 
    name: dbus
    enabled: yes

- name: Enable polkit
  service: 
    name: polkitd
    enabled: yes
# sway
