---
free_packages:
  - vim
  - htop
  - neofetch
  - neovim
  - zsh
  - alacritty
  - anki 
  - telegram-desktop
  - Thunar
  - vscode
  - mpv
  - qbittorrent
  - wget
  - syncthing
  - brightnessctl
  - pipewire
  - connman
  - pass
  - lazygit 
  # SWAY
  # Troubles:
  # https://www.reddit.com/r/voidlinux/comments/hgm4ig/void_sway_troubleshooting_reminder/
  # https://www.reddit.com/r/voidlinux/comments/nab764/sway_not_working/
  # https://github.com/swaywm/sway/wiki/Running-Sway-without-systemd
  # https://docs.voidlinux.org/config/graphical-session/graphics-drivers/index.html
  - dbus-elogind
  - polkit
  - elogind
  - mesa-dri
  - xorg-fonts
  - gvfs
  - wayland
  - sway
  - swaylock
  - Waybar

non_free_packages:
  - obsidian
  - google-chrome
  - spotify

non_free_packages_flatpak_id:
  - md.obsidian.Obsidian
  - com.google.Chrome
  - com.spotify.Client

cargo:
  - yofi

