---

- name: Change user shell to zsh
  user:
    name: "{{ username }}"
    shell: /bin/zsh

# sway
- name: Enable dbus
  service: 
    name: dbus
    enabled: yes

- name: Enable polkit
  service: 
    name: polkitd
    enabled: yes
# sway
